// <auto-generated />
using System;
using Etf.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Etf.Infrastructure.Migrations
{
    [DbContext(typeof(TradingDb))]
    [Migration("20260908191123_OrderExecution")]
    partial class OrderExecution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Etf.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Available")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Reserved")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasCheckConstraint("account_nonnegative", "\"Available\" >= 0 AND \"Reserved\" >= 0");
                        });
                });

            modelBuilder.Entity("Etf.Domain.Fund", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Symbol");

                    b.ToTable("Funds");
                });

            modelBuilder.Entity("Etf.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Etf")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal?>("ExecutedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ExecutionPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("LimitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Reservation")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Etf");

                    b.HasIndex("ClientId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("order_result_valid", "(\"Status\" = 'PendingExecution' AND \"ExecutionPrice\" IS NULL AND \"ExecutedAmount\" IS NULL AND \"RejectionReason\" IS NULL AND \"FinalizedAt\" IS NULL)\nOR (\"Status\" = 'Executed' AND \"ExecutionPrice\" IS NOT NULL AND \"ExecutionPrice\" > 0 AND \"ExecutionPrice\" <= \"LimitPrice\"\n    AND \"ExecutedAmount\" IS NOT NULL AND \"ExecutedAmount\" = \"Quantity\" * \"ExecutionPrice\" AND \"RejectionReason\" IS NULL AND \"FinalizedAt\" IS NOT NULL)\nOR (\"Status\" = 'Rejected' AND \"ExecutionPrice\" IS NULL AND \"ExecutedAmount\" IS NULL AND \"RejectionReason\" IS NOT NULL\n    AND length(\"RejectionReason\") > 0 AND \"FinalizedAt\" IS NOT NULL)");

                            t.HasCheckConstraint("order_valid", "\"Quantity\" > 0 AND \"LimitPrice\" > 0 AND \"Reservation\" = \"Quantity\" * \"LimitPrice\"");
                        });
                });

            modelBuilder.Entity("Etf.Domain.OrderTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("\"ToStatus\" <> 'PendingExecution'");

                    b.HasIndex("OrderId", "ToStatus")
                        .IsUnique();

                    b.ToTable("OrderTransitions", null, t =>
                        {
                            t.HasCheckConstraint("transition_valid", "(\"FromStatus\" IS NULL AND \"ToStatus\" = 'PendingExecution')\nOR (\"FromStatus\" IS NOT NULL AND \"FromStatus\" = 'PendingExecution' AND \"ToStatus\" IN ('Executed', 'Rejected'))");
                        });
                });

            modelBuilder.Entity("Etf.Domain.Order", b =>
                {
                    b.HasOne("Etf.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Etf.Domain.Fund", null)
                        .WithMany()
                        .HasForeignKey("Etf")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Etf.Domain.OrderTransition", b =>
                {
                    b.HasOne("Etf.Domain.Order", null)
                        .WithMany("History")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Etf.Domain.Order", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
